src/util/gamma_picker.cpp
src/util/gamma_picker.h

Matches https://github.com/monero-project/monero/pull/7845 && https://github.com/monero-project/monero/pull/7821

Match Monero 0.17.2.3 decoy selection algo

---

CMakeLists.txt
Dockerfile

Commit 3aa0a9ec6b7043b0de1c50b404d09fd7404cdab2 in develop needs to use monero v0.18, otherwise the develop branch doesn't compile

update develop branch to v0.18

---

CMakeLists.txt

Closes #5
I don't know if this is the best way to solve it. Any better idea is appreciated.

fix(cmake): fix Mac error 'undefined symbols for architecture'

---

src/rpc/light_wallet.cpp
src/wire/json/read.cpp
src/wire/read.cpp
src/wire/read.h

This is similar to the other updated #53 PR, but without the unit tests. Will just merge after a few days because this code needs to be updated.

Simplified wire integer handling

---

src/db/storage.cpp
src/error.cpp
src/error.h

Fix rescan to invalid blockchain height bug

---

src/wire/msgpack/base.h
src/wire/msgpack/read.h

- Add missing `#include <limits>`

Fix Slackware build

---

src/rpc/light_wallet.cpp

Add fee to get_address_txs

---

docs/administration.md
src/rest_server.cpp
src/rpc/admin.cpp
src/rpc/admin.h

Someone requested this for their UX. Its preferably to do this in the frontend itself, but whatever.

Add /validate endpoint to admin REST api

---

src/rest_server.cpp

This should fix the reports of "too many files open" - hopefully. Looking for testers.

Fix too many open files issue with ZeroMQ

---

src/rest_server.cpp
src/rpc/light_wallet.cpp
src/wire/field.h
tests/unit/CMakeLists.txt
tests/unit/rest.test.cpp
tests/unit/scanner.test.cpp
tests/unit/scanner.test.h

This adds some basic unit tests for the REST api. More tests might come shortly - particularly the admin tests.

Add basic REST tests

---

CMakeLists.txt
tests/unit/rest.test.cpp
tests/unit/wire/read.test.cpp

Downgrade CXX17 features to CXX14

---

CMakeLists.txt
Dockerfile

Updates the dockerfile to use a newer Monero release.

Update dockerfile on release to 0.18.3.3

---

src/admin_main.cpp

This adds delete webhook commands previously available on admin rest to the cli command list.

Add webhook deletion to admin cli

---

src/rest_server.cpp

Fix divide by zero in subaddresses n_maj

---

CMakeLists.txt
tests/unit/scanner.test.cpp

A bit of a hack, but should get the `develop` and eventually `master` branches working again.

Fixing build (upstream ZMQ CMake changes)

---

README.md
src/rest_server.cpp
src/rest_server.h
src/util/http_server.h
tests/unit/wire/read.write.test.cpp

As the title says. If CI passes this will get merged quickly.

Fix 0.3 build with newer asio (1.87+) versions. Min boost is now 1.66

---

CMakeLists.txt
Dockerfile

* Update to 22.04 (20.04 has reached end-of-life)
* Update local build of expat and ubound versions to latest
* Remove unnecessary package installs
* Update CMake file to reflect changes needed for static build

Changes to the dockerfile [0.3]

---

Dockerfile

Reduce docker image size by 100 MiB

---

src/rest_server.cpp

The change to `boost::beast` changed how timeouts were handled by the server. Each new REST request had a 5-second timeout. This prevented clients from having long running connections. This made things in `lwsf` not work properly, as the connection was terminated quite aggressively server-side.
The new change is to have aggressive 5-second timeouts for **new** connections, and then longer 5-minute timeouts for sessions with a valid login. Neither value is configurable (yet), but can be extended easily to handle that.

Set longer timeouts for requests after login

---

src/db/storage.cpp
src/rpc/light_wallet.cpp
src/scanner.cpp
tests/unit/rest.test.cpp
tests/unit/scanner.test.cpp

Just as the title says. This should easily pass tests!

Fix ringct+coinbase output tracking, and update rescan rollbacks

---

src/db/storage.cpp
src/rpc/light_wallet.cpp
src/scanner.cpp
tests/unit/rest.test.cpp
tests/unit/scanner.test.cpp

Same as #178 but on release branch.

Fix ringct+coinbase output tracking, and update rescan rollbacks [0.3]
