src/rpc/daemon_zmq.cpp, src/rpc/light_wallet.cpp, src/scanner.cpp, src/wire/crypto.h
Edit:
Worth highlighting, this code won't be able to identify bp+ outputs at the fork height with Monero's current master branch because I assumed that [this PR will be merged](https://github.com/monero-project/monero/pull/8277)
([here](https://github.com/j-berman/monero-lws/commit/f0be525daeb2d272d54684bdde877d62f7a4e6e3) is the code that *would* work with master that I assume will not be needed)
=> Add support for view tags (+ epee misc util re-located)

src/rest_server.cpp, src/rpc/light_wallet.cpp, src/rpc/light_wallet.h
Ok did the easy thing and converted `per_kb_fee` to `per_byte_fee`
One thing: upon deeper inspection, it *looks* like the server shouldn't be masking the fee. Maybe you see something I don't.. but if the client "re-masks" *after* factoring in weight (as MyMonero does [here](https://github.com/mymonero/mymonero-core-cpp/blob/a53e57f2a376b05bb0f4d851713321c749e5d8d9/src/monero_fee_utils.cpp#L233), here's [the caller](https://github.com/mymonero/mymonero-core-cpp/blob/a53e57f2a376b05bb0f4d851713321c749e5d8d9/src/monero_transfer_utils.cpp#L435)), the fee calculation is different than it would otherwise be. Since wallet2 [seems to only mask once after weight is factored in](https://github.com/monero-project/monero/blob/9aab19f349433687c7aaf2c1cbc5751e5912c0aa/src/wallet/wallet2.cpp#L336), and …
=> per_kb_fee -> per_byte_fee

CMakeLists.txt, Dockerfile, src/CMakeLists.txt
Requested on [the reddit](https://www.reddit.com/r/Monero/comments/sll4bi/monero_meet_20220205_fees_monerolws_and_network/hvw1zzw/)
If you're already running `monerod` on the same machine you'd like to host `monero-lws`, you can use this Dockerfile to spin up a `monero-lws` docker container by running the following commands on Linux:
```
docker build -t monero-lws .
docker run --network="host" --restart unless-stopped --name="monero-lws" -v bitmonero-lws:/home/monero-lws/.bitmonero/light_wallet_server monero-lws --log-level=4
docker exec monero-lws monero-lws-admin --db-path="home/monero-lws/.bitmonero/light_wallet_server" --help
docker exec monero-lws monero-lws-admin --db-path="home/monero-lws/.bitmonero/light_wallet_server" debug_database | json_pp
```
On Linux, `--network="host"` will …
=> Adding a Dockerfile

Dockerfile
@vdo @sethforprivacy @j-berman @selsta
Egg on face for not testing the `Dockerfile`. Finally installed `Docker` to confirm these changes work. The custom downloading/building of `expat` and `unbound` comes from @sethforprivacy `Docker` stuff for `monerod`. These changes are likely to be cherry-picked onto `master` and `develop` eventually.
Also see latest push on `release-v0.2_0.18`. I missed a commit from @j-berman , didn't include it here because its technically already been reviewed (its from the `release-v0.1_0.17` branch).
=> Use custom unbound in Dockerfile (fix static linking)

CMakeLists.txt, Dockerfile
`HIDAPI` is not needed to build upstream `monerod`. This detects the missing library, and omits it from the include and linking stages. The `Dockerfile` was also updated to omit the installation of `HIDAPI` since its not needed.
I manually verified that this still works when `HIDAPI` is present.
=> Detect missing HIDAPI in Cmake

CMakeLists.txt
This will be necessary to read headers from upstream Monero as changes are made.
=> Bump CXX version to C++14

src/wire/json/write.cpp, src/wire/json/write.h, src/wire/read.cpp, src/wire/read.h, src/wire/write.h
* Integer conversion checks in src/wire/read.h
* Missing "boolean" function in wire::writer and derived types
This is the same as #53 but without the unit tests and onto the 0.2 release branch. Trying to strip the review to its core components to make it easier.
=> Fixed two bugs in wire:

CMakeLists.txt, src/rpc/light_wallet.cpp, src/wire/json/read.cpp, src/wire/json/write.cpp, src/wire/json/write.h, src/wire/read.h, src/wire/write.h, tests/CMakeLists.txt, tests/unit/CMakeLists.txt, tests/unit/framework.test.cpp, tests/unit/framework.test.h, tests/unit/lest.hpp, tests/unit/main.cpp, tests/unit/wire/CMakeLists.txt, tests/unit/wire/base.test.h, tests/unit/wire/json/CMakeLists.txt, tests/unit/wire/json/read.write.test.cpp, tests/unit/wire/read.test.cpp, tests/unit/wire/read.write.test.cpp
* Integer conversion checks in src/wire/read.h
* Missing "boolean" function in wire::writer and derived types
This is similar to #52 but should fix the integer checking issue, and adds unit tests for the wire code. Eventually the two fixes will be PR'ed onto the release branch, but the unit tests will likely not (at least not initially).
I doubt many people will want to go through this review, so I will leave it here for ~2 weeks and then just merge. Look out for `lest.hpp` which is from another project, but somewhat easy to review.
=> Added unit tests, and fixed two bugs:

CMakeLists.txt, docs/administration.md, src/CMakeLists.txt, src/admin_main.cpp, src/db/data.h, src/db/storage.cpp, src/db/storage.h, src/rest_server.cpp, src/rest_server.h, src/rpc/CMakeLists.txt, src/rpc/admin.cpp, src/rpc/admin.h, src/server_main.cpp
This makes some of the commands currently only available in `monero-lws-admin` via REST. Some of the commands are intentionally omitted for security purposes. The admin REST commands can be accessed via a separate port or separate namespace/prefix on the same port.
=> Add support for admin REST server

src/wire/CMakeLists.txt, src/wire/field.h, src/wire/msgpack.h, src/wire/msgpack/CMakeLists.txt, src/wire/msgpack/base.h, src/wire/msgpack/error.cpp, src/wire/msgpack/error.h, src/wire/msgpack/fwd.h, src/wire/msgpack/read.cpp, src/wire/msgpack/read.h, src/wire/msgpack/write.cpp, src/wire/msgpack/write.h, src/wire/read.h, src/wire/write.h, tests/unit/CMakeLists.txt, tests/unit/wire/msgpack/CMakeLists.txt, tests/unit/wire/msgpack/read.write.test.cpp, tests/unit/wire/read.write.test.cpp
Support for webhooks is in the works, which requires variable sized records stored in the DB. I have decided to store this data using msgpack encodings.
This encoding library supports both integer and string keys for object types. The reader can transparently support both, while the writer requires a flag to toggle integer or string key output.
Types must specify an integer key to use with msgpack, so some existing code wouldn't work correctly with msgpack directly. The webhook DB records will use integer keys for performance/compaction reasons.
=> Adding msgpack support to ::wire:: library

Dockerfile
This updates the`dockerfile` on the `develop` branch to use the latest `monero` release. I have verified this still builds (on the `develop` branch). If there are no objections to this PR, I will update/cherry-pick to the `monero-lws` release branch and master branches.
=> Updating dockerfile to newer monerod release

src/util/gamma_picker.cpp
[wallet2](https://github.com/monero-project/monero/blob/f307621678c24ee7ca158fde38080d787d678733/src/wallet/wallet2.cpp#L6454-L6455) + [consensus](https://github.com/monero-project/monero/blob/f307621678c24ee7ca158fde38080d787d678733/src/cryptonote_core/blockchain.cpp#L3531-L3536) allow a user to spend an output that's in a block 9 blocks prior to the final block in the chain, since the output is eligible to be included in the *next* block at that point (see discussion [here](https://github.com/monero-project/monero/pull/8794#issuecomment-1478116268)). The decoy selection algo should therefore apply the same criteria when selecting decoys.
The PR to change the decoy selection algo in the monero repo is still open here: https://github.com/monero-project/monero/pull/8794
=> Decoy selection algo off-by-1

docs/administration.md, src/CMakeLists.txt, src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/db/storage.h, src/error.cpp, src/error.h, src/lmdb/msgpack_table.h, src/rest_server.cpp, src/rest_server.h, src/rpc/admin.cpp, src/rpc/admin.h, src/scanner.cpp, src/server_main.cpp, src/wire/crypto.h, src/wire/field.h, src/wire/msgpack/base.h, src/wire/msgpack/write.h, src/wire/read.h, src/wire/traits.h, src/wire/uuid.h, src/wire/write.h, tests/unit/CMakeLists.txt, tests/unit/db/CMakeLists.txt, tests/unit/db/storage.test.cpp, tests/unit/db/storage.test.h, tests/unit/db/webhook.test.cpp, tests/unit/rpc/CMakeLists.txt, tests/unit/rpc/admin.test.cpp
This is a "still-in-progress" PR/patch to add webhook support to `monero-lws-daemon`. I would like to add some unit testing before officially merging this PR. There's also some trivial stuff I noticed - wrong copyright dates for instance. This branch should be considered "beta" - the expectation is that is should be near usable in a production environment.
This PR currently supports "`tx-confirmation`" only - a Monero address + (optional) payment_id is sent via REST, along with a provided URL. The URL is then invoked 1+ times when an output for that address+payment_id pair is found on the blockchain. The number of URL invokes is determine in the original API call - the user specifies the number of confirmations needed (defaults to 1).
Please respond to this PR if you need help using this …
=> Added webhook (tx-confirmation) support

src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/scanner.cpp
Someone has privately requested that webhooks include the transaction fee. This was never reported by the MyMonero API, so the LWS-db doesn't even track it. This contains the first in-place update to the DB to get the transaction fee working.
Limitations:
* Only ring-ct transactions are supported (Jan 2017). Older transactions will be reported as `0` for fee.
* A rescan is not performed of existing transactions in the DB, instead the fee is marked as `0`. A rescan will correctly update the fee.
* The fee is not returned in the REST API, only the web hook API.
=> Add tx fee to the db and track for webhooks

src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/db/storage.h, src/rpc/client.cpp, src/rpc/client.h, src/rpc/daemon_pub.cpp, src/rpc/daemon_pub.h, src/rpc/daemon_zmq.cpp, src/rpc/daemon_zmq.h, src/scanner.cpp, src/wire/wrapper/defaulted.h
Getting zero-confirmation notifications via webhooks requires the `--sub` option (and `monerod` must have `--zmq-pub` set as well). The transactions _do not_ show up in the REST API until 1 confirmation. The notifications are nearly instant (everything uses pub/sub instead of polling).
Zero-confirmations in the REST API _might be_ added in the future but that is a little more involved (unless I can come up with an alternative implementation).
The block number and output numbers are omitted from zero-conf output, since they lack valid values.
=> Add zero-confirmation support to webhooks (only)

src/rpc/client.cpp
The current timeout spews information to the log too aggressively (the block time is approximately 2 minutes).
=> Change ZMQ sub timeout

docs/administration.md, docs/zmq.md, src/db/account.cpp, src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/rpc/client.cpp, src/rpc/client.h, src/scanner.cpp, src/server_main.cpp, src/wire/adapted/span.h
This PR adds ZeroMQ publish support for webhooks. When configured, all webhooks will be simulcast over ZeroMQ. Webhooks can also be created with the http destination "zmq" to indicate that notifications should only happen over ZeroMQ.
There is an `index` field to help receivers detect gaps (ZeroMQ pub/sub drops when the highwater mark is reached). All of this is mentioned in the updated documentation.
Forgot to mention that it supports both JSON and Msgpack. Subscribers choose which feed they want.
=> Add ZMQ-PUB support for webhooks

src/server_main.cpp
Add an option for a config file. This is useful for the upcoming RMQ PR which has a login option.
=> Add config-file option

src/error.cpp, src/error.h, src/rpc/json.h, src/scanner.cpp
This changes the `get_blocks_fast` error response to a non-shutdown call. The error from the server is printed, and the scan threads are reset. The server has a few error cases that seem to come up when a chain reorg is happening.
=> Do not exit when monerod returns json-rpc error for block fetching

docs/administration.md, docs/zmq.md, src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/db/storage.h, src/rest_server.cpp, src/rest_server.h, src/rpc/admin.cpp, src/rpc/webhook.h, src/scanner.cpp, src/scanner.h, src/server_main.cpp
Adds webhooks on new account creation _request_. Currently the server must be polled for new account creation requests. Auto-accepting all account creation requests still not possible (yet!).
=> Webhooks for New Accounts

CMakeLists.txt, docs/rmq.md, src/error.cpp, src/error.h, src/rpc/CMakeLists.txt, src/rpc/client.cpp, src/rpc/client.h, src/server_main.cpp
This will need a rebase after #79 gets merged. RabbitMQ is an optional dependency that defaults to "OFF".
The CI has **not** been updated yet to verify RabbitMQ enabled builds (it only checks the OFF case).
=> Add RabbitMQ support for payment hooks

src/wire/write.h
I broke the `debug_database` command when updating `::wire` to be more compatible with upstream monero. This resulted in bogus values being output to the terminal with that command, but did not affect the values in the db.
Another fix will be needed when `::wire` in upstream monero goes active (because there is no filter option in upstream monero at the moment), but I will put off such changes for now.
=> Fix lifetime bug in wire::as_array (debug_database)

src/scanner.cpp
After transaction version 2, coinbases have public `amount`, but are still logically placed in the `0` category for outputs. I have in-progress unit tests that catch this, and I wanted to post this ASAP (so I did a dedicated PR).
=> Fix output_id bug with coinbase transactions

src/db/account.cpp, src/db/account.h, src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/db/storage.h, src/error.cpp, src/error.h, src/lmdb/msgpack_table.h, src/rest_server.cpp, src/rest_server.h, src/rpc/light_wallet.cpp, src/rpc/light_wallet.h, src/scanner.cpp, src/scanner.h, src/server_main.cpp, src/wire/adapted/array.h, src/wire/write.h, tests/unit/db/CMakeLists.txt, tests/unit/db/data.test.cpp, tests/unit/db/subaddress.test.cpp
This brings subaddress support to MLWS by implementing the [working draft for LWS subaddresses](https://github.com/monero-project/meta/pull/647). If the spec changes before being finalized, then MLWS will be modified to match the spec changes.
=> Add (working draft) subaddress support

src/wire.h, src/wire/json/read.cpp, src/wire/json/read.h, src/wire/json/write.cpp, src/wire/json/write.h, src/wire/msgpack/read.cpp, src/wire/msgpack/read.h, src/wire/msgpack/write.cpp, src/wire/msgpack/write.h, src/wire/read.h, src/wire/write.h
The "upstream" `::wire` interface (being proposed in monero repo) does not have an `enumeration` function, because there is no use for it. This removes that functionality in preparation for merging with upstream. This does mean that msgpack can no longer output an integer _instead of a string_, but that may be the for the best for compatibility reasons.
=> Remove enumeration function from ::wire reading and writing

CMakeLists.txt
The `master` and `develop` builds will soon [need C++17](https://github.com/monero-project/monero/pull/9072) support enabled.
=> Update cxx version to C++17

src/rest_server.cpp, src/rest_server.h, src/server_main.cpp
The title says it all - you no longer need glue code to accept new addresses/accounts. The downside is there is **no limit** on number of accounts, but there is a limit on the number of pending creation requests. 
Also note that I have yet to implement an account deletion function! So I would only use this option with extreme caution, as someone could fill-up your database (account deletion is a feature to be worked on shortly).
=> Add option to auto-accept new account creation

src/CMakeLists.txt, src/rpc/CMakeLists.txt, src/rpc/client.cpp, src/rpc/client.h, src/scanner.cpp, tests/unit/CMakeLists.txt, tests/unit/db/CMakeLists.txt, tests/unit/db/chain.test.cpp, tests/unit/db/chain.test.h, tests/unit/scanner.test.cpp
This adds tests for `db::storage::sync_chain`, `scanner::sync_chain`, and `scanner::run`.
These tests help make sure forks/reorgs are handled correctly, and will help with ensuring no new bugs appear with "chain hardening".
=> Add unit tests for chain syncing

tests/unit/wire/read.test.cpp
Now that C++17 has landed in develop, we can silence some of the warnings about integers out of range.
=> Fix warnings in unit tests

src/db/storage.cpp, src/db/storage.h, tests/unit/db/chain.test.cpp, tests/unit/scanner.test.cpp
This prevents the daemon from attempting to fork the blockchain past a hard-coded checkpoint. The daemon cannot rollback past a checkpoint, so this can only happen with a "bad" daemon.
=> Refuse chain rollback past a checkpoint

src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/db/storage.h, src/rpc/daemon_zmq.cpp, src/rpc/daemon_zmq.h, src/scanner.cpp, src/server_main.cpp, src/util/CMakeLists.txt, src/util/blocks.cpp, src/util/blocks.h, tests/unit/db/chain.test.cpp, tests/unit/db/webhook.test.cpp, tests/unit/scanner.test.cpp
This adds basic chain hardening to the daemon, for slightly untrusted daemons. It is still recommended that you run your own node, as there are more features like JSON memory unpacking limits (similar to what the daemon had to endure).
When `--untrusted-daemon` is enabled:
* Every block `prev_id` is verified, to ensure a chain
* Every "hard-coded" checkpoint has its block hash verified
* The two above mean that you cannot easily spoof old blocks - only blocks newer than a checkpoint
* Every transaction hash is computed and verified against the block hash list
* The PoW is verified for blocks newer than any checkpoints, forcing a malicious daemon to spend resources to generate fake blocks
* The block height, hash, and difficulty are periodically printed to help assist in detecting …
=> Basic "chain hardening" for slightly untrusted daemons

src/rpc/webhook.h
The prior patch wasn't carried over when moving code around.
=> Fix response code check for webhooks (again)

src/rpc/light_wallet.cpp
I thought I fixed #69, but I accidentally set one of the array fields to required.
=> Make arrays optional in light_wallet_server api

src/db/storage.cpp
I found an error case with the invalid chain rollback detection - when the daemon is still syncing it sends older blocks. The easiest thing to do (for now) is to update the error message to let the user know they must sync the daemon before using LWS.
=> Update chain rollback log message

docs/zmq.md, src/db/fwd.h, src/db/storage.h, src/rpc/CMakeLists.txt, src/rpc/fwd.h, src/rpc/lws_pub.cpp, src/rpc/lws_pub.h, src/rpc/webhook.h, src/scanner.cpp, src/wire/write.h
A little different than I intended, but this adds a ZMQ-PUB for recently scanned addresses. The address is sent along with the last block height and hash. This is useful for tracking the internal scan state in real-time, as each thread reports independent results.
=> ZMQ pub blocks

docs/zmq.md, src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/db/storage.h, src/rpc/admin.cpp, src/scanner.cpp, tests/unit/db/webhook.test.cpp
This adds support to webhook/zmq for spend notification. The use case is detecting unexpected spending of funds.
=> ZMQ Pub Spends

src/scanner.cpp
A simple fix for displaying info messages on the "leader_thread" (used when `--untrusted-daemon` is enabled).
=> Fix "leader_thread" logic (for info messages)

src/db/account.cpp, src/db/account.h, src/db/storage.cpp, tests/unit/db/chain.test.cpp, tests/unit/db/webhook.test.cpp, tests/unit/scanner.test.cpp
* lws::account height update should only go up.
* Webhook confirmations can start after first new block
* Webhook confirmations could face a rescan
Found these issues while digging deeper in the remote scanning code (although not related to that code). This will get merged relatively soon as these bugs need to be back-ported to release branch.
=> Fix several bugs:

src/db/storage.cpp, src/db/storage.h, tests/unit/db/chain.test.cpp, tests/unit/db/webhook.test.cpp
The last PR still had another bug involving a scan height index. I added unit tests to ensure this index is correctly update (or not changed) during complex scanning conditions (rescans, forks, duplicate check-ins).
=> Fix scan height (db) bug on account check-ins

src/db/storage.cpp, tests/unit/db/webhook.test.cpp
Found yet-another bug in the webhook event handling. This time, if an account does a partial re-scan, it could resend web hook events (instead of suppressing them). This PR fixes that, and adds some unit tests for the scenario.
=> Fix webhook bug on overlapping rescan

src/rest_server.cpp
After a read timeout, the thread-local ZMQ client is expecting a read, and not send on the REQ socket. This attempts to read+discard 1 message before retrying the REQ send. This has proven effective at recovering from a temporarily unavailable daemon.
=> Fix ZeroMQ invalid REQ/REP state after read timeout.

src/rest_server.cpp, src/rpc/light_wallet.cpp, src/rpc/light_wallet.h
Requested privately. Mostly a relay to from the daemon. Possibly useful to clients that only have access to LWS REST.
=> Add (non-standard) 'daemon_status' endpoint to REST API

src/CMakeLists.txt, src/db/storage.cpp, src/lmdb/CMakeLists.txt, src/lmdb/lws_database.cpp, src/lmdb/lws_database.h
Fixing a bug in the lmdb adaption code is [taking a while](https://github.com/monero-project/monero/pull/9290) in the upstream monero repo. So I merged a fixed version in this code repo, while awaiting the fixes upstream. This will most likely be reverted once its fixed.
=> Pull in fixes to lmdb::database from monero PR

src/CMakeLists.txt, src/client_main.cpp, src/db/account.h, src/db/data.cpp, src/db/data.h, src/db/storage.cpp, src/db/storage.h, src/rpc/client.cpp, src/rpc/client.h, src/rpc/fwd.h, src/rpc/scanner/CMakeLists.txt, src/rpc/scanner/client.cpp, src/rpc/scanner/client.h, src/rpc/scanner/commands.cpp, src/rpc/scanner/commands.h, src/rpc/scanner/connection.cpp, src/rpc/scanner/connection.h, src/rpc/scanner/fwd.h, src/rpc/scanner/queue.cpp, src/rpc/scanner/queue.h, src/rpc/scanner/read_commands.h, src/rpc/scanner/server.cpp, src/rpc/scanner/server.h, src/rpc/scanner/write_commands.cpp, src/rpc/scanner/write_commands.h, src/scanner.cpp, src/scanner.h, src/server_main.cpp, tests/unit/scanner.test.cpp
This is the first cut at remote scanning in LWS. It took a while to complete because a custom TCP implementation using ASIO was done - ZMQ sockets were too limited in their capabilities for the task.
There's lots of code here, so I will leave for a bit as I perform additional testing on this, including performance tests. I'm still uncertain on how this will perform with lots of accounts, etc.
=> Add support for remote scanning via custom TCP

src/lmdb/lws_database.h
`result_of` was deprecated in C++17. This silences warnings on several platforms.
=> Replace deprecated result_of with decltype

src/rpc/scanner/server.cpp, src/rpc/scanner/server.h, src/rpc/scanner/write_commands.h, src/scanner.cpp
As the title suggests. Found these primarily with an impromptu code audit while making the ASIO update changes.
=> Fix several bugs found in new server scanner code

CMakeLists.txt, Dockerfile, src/CMakeLists.txt
The `Dockerfile` will build against the `develop` branch once this [upstream PR](https://github.com/monero-project/monero/pull/9530) is merged.
=> Update Dockerfile and CMake files to build develop/master

CMakeLists.txt, src/CMakeLists.txt, src/net/zmq_async.h, src/rest_server.cpp
As the title says. I punted on a ASIO stackless implementation, as things got a little messy. Only one stack is spawned at a time, so the memory and setup time is kept to a minimum.
The only blocking calls left on the REST server are the optional HTTP callbacks for account creation in the `/login` endpoint. Still working on testing that, as I am moving all HTTP clients away from `epee` and to `boost::beast`.
=> /get_random_outs is now fully async using stackful coroutines

src/client_main.cpp, src/net/zmq_async.cpp, src/net/zmq_async.h, src/rest_server.cpp, src/rest_server.h, src/rpc/client.cpp, src/rpc/client.h, src/rpc/scanner/client.cpp, src/rpc/scanner/client.h, src/rpc/scanner/connection.cpp, src/rpc/scanner/connection.h, src/rpc/scanner/read_commands.h, src/rpc/scanner/server.cpp, src/rpc/scanner/server.h, src/rpc/scanner/write_commands.h, src/scanner.cpp, src/scanner.h
* Convert boost::asio::io_service to boost::asio::io_context
* Drop usage of GET_IO_SERVICE macro from monero
* Refactor REST server to manage resources better
=> Update boost::asio usage to conform to newer standards:

src/client_main.cpp, src/net/CMakeLists.txt, src/net/http/CMakeLists.txt, src/net/http/client.cpp, src/net/http/client.h, src/net/http/slice_body.h, src/rest_server.cpp, src/rpc/client.cpp, src/rpc/client.h, src/rpc/rates.h, src/rpc/scanner/server.cpp, src/rpc/scanner/server.h, src/rpc/webhook.h, src/scanner.cpp, src/scanner.h, src/server_main.cpp, tests/unit/net/CMakeLists.txt, tests/unit/net/http/CMakeLists.txt, tests/unit/net/http/client.test.cpp, tests/unit/scanner.test.cpp
As the title suggests, this removes all blocking epee HTTP client code and moves to an async `boost::beast` implementation. The REST endpoint `/login` is now always non-blocking, even with account creation webhooks. The scanner no longer blocks for webhooks, and instead queues up requests. The rate exchange fetch code is also now async.
=> Switch from epee http client to boost::beast. All HTTP now non-blocking.

.github/workflows/build-ubuntu.yml, src/rest_server.cpp, src/rpc/scanner/client.cpp, src/rpc/scanner/server.cpp, src/rpc/scanner/write_commands.h, src/scanner.cpp
I missed some deprecated things in Boost ASIO so the build fails with Boost 1.87. This _should_ fail the macOS CI as upstream Monero does not have merged features to make Boost 1.87 work.
The relevant monero PR to [make Boost 1.87 work](https://github.com/monero-project/monero/pull/9628)
=> Update deprecated features removed in Boost ASIO 1.87

src/error.cpp, src/error.h, src/rest_server.cpp
This PR includes a small enhancement on the `get_unspent_outs` method, which returned the error `lws::error:account_not_found` when the amount received is not enough to satisfy the requested amount, in turn causing the `HTTP 403 Forbidden` error. A new error `lws::error:not_enough_amount` has been introduced that replaces `lws::error::account_not_found` in this specific case, also the `bad_request` method has been modified to correctly handle this new error and return the `HTTP 400 Bad Request` error according to the official light wallet API [get_unspent_outs specification](https://github.com/monero-project/meta/blob/master/api/lightwallet_rest.md#get_unspent_outs).
=> Adjust get_unspent_outs return error according to API standard

.github/workflows/build-ubuntu.yml, .gitmodules, CMakeLists.txt
This makes the build process much easier - `monero` repo is now a git submodule. A single recursive submodule command makes it harder to screw up as the correct monero branch is always used.
The old process is still supported as it's a bit quicker, uses less space, and building the LWS unit tests doesn't trigger building of the monero unit tests.
The CI was also updated to verify that both the old and new style building work.
=> Add optional support for git submodule building

CMakeLists.txt, src/rest_server.cpp, src/rpc/light_wallet.cpp, src/rpc/light_wallet.h, tests/unit/rest.test.cpp
As the title says. This requires a corresponding patch in the daemon (on `master`), so the CI should fail. The CI will be re-run once the associated patch gets merged, and then this PR will get merged after.
=> Add support for dynamic fees over ZMQ

CMakeLists.txt, src/rest_server.cpp, src/rpc/light_wallet.cpp, src/rpc/light_wallet.h, tests/unit/rest.test.cpp
This requires #165 and a corresponding patch to `release-v0.18` in monero upstream (so the CI should fail). The CI will be re-run, and this PR merged once those changes are merged.
=> Add support for dynamic fees over ZMQ [0.3]
